openapi: 3.0.4
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks and users
servers:
  - url: 'http://api.example.com/v1'
    description: Production server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - name
        - email
        - password
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
        name:
          type: string
          example: Pranav
        email:
          type: string
          format: email
          example: pranav@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: secure123
        role:
          type: string
          enum:
            - admin
            - lead
            - member
          default: member
        status:
          type: string
          enum:
            - active
            - busy
            - unavailable
          default: active
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the user was created
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: pranav@example.com
        password:
          type: string
          format: password
          example: secure123
    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token
        refreshToken:
          type: string
          description: JWT refresh token
        user:
          $ref: '#/components/schemas/User'
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Invalid credentials
tags:
  - name: Authentication
    description: Endpoints related to auth
  - name: User Management
    description: Endpoints related to users
  - name: Task Management
    description: Endpoints related to tasks
paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Create a new user account
      description: 'Register a new user with name, email, and password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: Pranav
                email:
                  type: string
                  format: email
                  example: pranav@example.com
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: secure123
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Authenticate user and get JWT tokens
      description: Authenticate a user with email and password to receive access and refresh tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Invalidate refresh token
      description: Log out the current user by invalidating their refresh token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh access token
      description: Get a new access token using a valid refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
                  description: Valid refresh token
      responses:
        '200':
          description: New access token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: New JWT access token
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users:
    get:
      tags:
        - User Management
      summary: Get all users
      description: Returns a list of all registered users
      responses:
        '200':
          description: A JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1users/post/requestBody/content/application~1json/schema'
    post:
      summary: Create a new user
      description: Add a new user to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  example: 123e4567-e89b-12d3-a456-426614174000
                name:
                  type: string
                  example: Alice
                email:
                  type: string
                  format: email
                  example: alice@example.com
              required:
                - id
                - name
                - email
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/paths/~1users/post/requestBody/content/application~1json/schema'
  /tasks:
    paths:
      /auth/login:
        get:
          tags:
            - Task Management
          summary: Get all tasks
          description: Returns a list of all tasks
          responses:
            '200':
              description: A JSON array of tasks
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: 987e6543-e21b-45d6-a789-426614174111
                        title:
                          type: string
                          example: Finish homework
                        description:
                          type: string
                          example: Complete math and science homework by tonight
                        status:
                          type: string
                          enum:
                            - pending
                            - in-progress
                            - done
                          example: pending
                        assignedTo:
                          $ref: '#/paths/~1users/post/requestBody/content/application~1json/schema'
                      required:
                        - id
                        - title
                        - status
