openapi: 3.0.4
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks and users
servers:
  - url: 'http://api.example.com/v1'
    description: Production server
tags:
  - name: Authentication
  - name: User Management
  - name: Task Management
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
        - role
        - status
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
        name:
          type: string
          example: Pranav
        email:
          type: string
          format: email
          example: pranav@example.com
        role:
          type: string
          enum:
            - admin
            - lead
            - member
          default: member
        status:
          type: string
          enum:
            - active
            - busy
            - unavailable
          default: active
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the user was created
    RegisterRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: Pranav
        email:
          type: string
          format: email
          example: pranav@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: secure123
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: pranav@example.com
        password:
          type: string
          format: password
          example: secure123
    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token
        refreshToken:
          type: string
          description: JWT refresh token
        user:
          $ref: '#/components/schemas/User'
    RefreshTokenRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          description: Valid refresh token
    RefreshTokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: New JWT access token
    Task:
      type: object
      required:
        - id
        - title
        - status
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        title:
          type: string
          description: Task title
        description:
          type: string
          description: Task description
        status:
          type: string
          enum:
            - pending
            - in-progress
            - completed
          default: pending
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the task was created
    CreateTask:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Task title
        description:
          type: string
          description: Task description
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: Invalid credentials
paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/logout:
    post:
      tags:
        - Authentication
      security:
        - bearerAuth: []
      summary: Logout user
      responses:
        '200':
          description: Logged out successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: New access token issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'
        '401':
          description: Invalid refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/me:
    get:
      tags:
        - User Management
      summary: Get logged-in user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tasks:
    get:
      tags:
        - Task Management
      security:
        - bearerAuth: []
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags:
        - Task Management
      security:
        - bearerAuth: []
      summary: Create task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTask'
      responses:
        '201':
          description: Task created
  '/tasks/{taskId}':
    delete:
      tags:
        - Task Management
      security:
        - bearerAuth: []
      summary: Delete task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted
