openapi: 3.0.4
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks and users
servers:
  - url: 'http://api.example.com/v1'
    description: Production server
  - url: 'http://staging-api.example.com'
    description: Staging server
tags:
  - name: User Management
    description: Endpoints related to users
  - name: Task Management
    description: Endpoints related to tasks
paths:
  /users:
    get:
      tags:
        - User Management
      summary: Get all users
      description: Returns a list of all registered users
      responses:
        '200':
          description: A JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1users/post/requestBody/content/application~1json/schema'
    post:
      summary: Create a new user
      description: Add a new user to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  example: 123e4567-e89b-12d3-a456-426614174000
                name:
                  type: string
                  example: Alice
                email:
                  type: string
                  format: email
                  example: alice@example.com
              required:
                - id
                - name
                - email
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/paths/~1users/post/requestBody/content/application~1json/schema'
  /tasks:
    paths:
      /auth/login:
        get:
          tags:
            - Task Management
          summary: Get all tasks
          description: Returns a list of all tasks
          responses:
            '200':
              description: A JSON array of tasks
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: 987e6543-e21b-45d6-a789-426614174111
                        title:
                          type: string
                          example: Finish homework
                        description:
                          type: string
                          example: Complete math and science homework by tonight
                        status:
                          type: string
                          enum:
                            - pending
                            - in-progress
                            - done
                          example: pending
                        assignedTo:
                          $ref: '#/paths/~1users/post/requestBody/content/application~1json/schema'
                      required:
                        - id
                        - title
                        - status
